export type SpriteData = string[];

// Character map:
// 'O' = Outline (Dark)       'P' = Primary (City accent)
// 'S' = Secondary (City neon) 'W' = White / Highlight
// 'B' = Brown (#8B4513)       'G' = Green (#22c55e)
// 'R' = Red (#ef4444)         'Y' = Yellow (#facc15)
// ' ' = Transparent

export const SPRITES: Record<string, SpriteData> = {

  // ── Node-specific sprites (matched by node ID) ─────────────────────

  'start': [
    "                    ",
    "         OOOO       ",
    "        OWWWO       ",
    "   OOOOOOOOOOOO     ",
    "  O WWWWWWWWWW O    ",
    "  O WPPPPPPPPW O    ",
    " O  WPPPPPPPPW  O   ",
    " O  WWWWWWWWWW  O   ",
    "  O            O    ",
    "   OOOOOOOOOOOO     ",
    "    O        O      ",
    "    O        O      ",
    "   OOOO    OOOO     ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'end': [
    "                    ",
    "        OOOO        ",
    "       OWWWWO       ",
    "      OW WW WO      ",
    "      OWWWWWWO      ",
    "       OOOOOO       ",
    "        O  O        ",
    "       OOOOOO       ",
    "      OO PP OO      ",
    "      O PPPP O      ",
    "      O PPPP O      ",
    "       OOOOOO       ",
    "        O  O        ",
    "       OO  OO       ",
    "       OO  OO       ",
    "                    ",
  ],

  'university-path': [
    "                    ",
    "                    ",
    "      OOOOOOOO      ",
    "     OPPPPPPPPPO    ",
    "    OPPPPPPPPPPPPO  ",
    "   OOOOOOOOOOOOOOO  ",
    "       O    O       ",
    "    OOOOOOOOOOO     ",
    "    OWWWWWWWWWO     ",
    "    OWSSOWWSSO      ",
    "    OWSSOWWSSO      ",
    "    OWWWWWWWWO      ",
    "    OWWSSWWWWO      ",
    "    OOOOOOOOOOO     ",
    "                    ",
    "                    ",
  ],

  'work-path': [
    "                    ",
    "                    ",
    "    OOOOOOOOOOO     ",
    "    OBBBBBBBBO      ",
    "   OBBBBBBBBBBO     ",
    "   OBBWWWWWBBBO     ",
    "   OBBWWWWWBBBO     ",
    "   OBBBBBBBBBBO     ",
    "    OBBBBBBBO       ",
    "    OO     OO       ",
    "     O     O        ",
    "     O     O        ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'art-path': [
    "                    ",
    "                    ",
    "   OOOOOOOOOOOOO    ",
    "   O  WWWWWWW  O    ",
    "   O WRRPPSSW  O    ",
    "   O WRPPPPSW  O    ",
    "   O WPPPPPSW  O    ",
    "   O WSSSPPPW  O    ",
    "   O WSSSSPWW  O    ",
    "   O  WWWWWWW  O    ",
    "   OOOOOOOOOOOOO    ",
    "        O O         ",
    "       OO OO        ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'travel-path': [
    "                    ",
    "                    ",
    "       OOOOO        ",
    "      O     O       ",
    "     O  P P  O      ",
    "    O    P    O     ",
    "    O PPPPPPP O     ",
    "    O P     P O     ",
    "    O P     P O     ",
    "     O       O      ",
    "      OOOOOOO       ",
    "     O OOOOO O      ",
    "    OOOOOOOOOOO     ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'corporate-path': [
    "                    ",
    "                    ",
    "    OOOOOOOOOOO     ",
    "    OSSSSSSSSSO     ",
    "    OSOOOOOOSOO     ",
    "    OSOWWWWOSO      ",
    "    OSOWWWWOSO      ",
    "    OSOWWWWOSO      ",
    "    OSOOOOOOSO      ",
    "    OSSSSSSSSSO     ",
    "    OOOOOOOOOOO     ",
    "       OOOOO        ",
    "     OOOOOOOOO      ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'creative-career-path': [
    "                    ",
    "                    ",
    "       OOO          ",
    "      OPPPO         ",
    "      OPPPO         ",
    "       OOO          ",
    "        O           ",
    "        O           ",
    "     OOOOOOO        ",
    "    O PPPPP O       ",
    "   O PPSPPPP O      ",
    "   O PPPPSPP O      ",
    "   O PPPPPPP O      ",
    "    OOOOOOOOO       ",
    "                    ",
    "                    ",
  ],

  'entrepreneur-path': [
    "                    ",
    "                    ",
    "    OOOOOOO         ",
    "   OWWWWWWWO        ",
    "   OWYYYYYYWO       ",
    "   OWYYYYYYWOO      ",
    "   OWYYYYYYWPO      ",
    "   OWYYYYYYWPO      ",
    "   OWWWWWWWWPO      ",
    "    OOPPPPPPO       ",
    "       OOOO         ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'relationship-decision': [
    "                    ",
    "     OOO    OOO     ",
    "    ORRRO  ORRRO    ",
    "   ORRRRROORRRRRO   ",
    "   ORRRRRRRRRRRRRO  ",
    "   ORRRRRRRRRRRRRO  ",
    "    ORRRRRRRRRRRO   ",
    "     ORRRRRRRRRO    ",
    "      ORRRRRRRO     ",
    "       ORRRRRO      ",
    "        ORRRO       ",
    "         ORO        ",
    "          O         ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'family-decision': [
    "                    ",
    "     OO   OO  OO    ",
    "    OWWO OWWO OO    ",
    "    OWWO OWWO       ",
    "     OO   OO        ",
    "     OO   OO        ",
    "    OPPO OPPO       ",
    "    OPPO OPPO       ",
    "     OO   OO        ",
    "    OO    OOO       ",
    "    OO     OO       ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'midlife-crisis': [
    "                    ",
    "                    ",
    "     OOOOOOOOO      ",
    "    O  W    W O     ",
    "   O   WW  WW  O    ",
    "   O    WWWW   O    ",
    "   O   WW  WW  O    ",
    "   O  W    W   O    ",
    "    O          O    ",
    "     OOOOOOOOO      ",
    "        OO          ",
    "      OOOOOO        ",
    "     OBBBBBBO       ",
    "      OOOOOO        ",
    "                    ",
    "                    ",
  ],

  'retirement': [
    "                    ",
    "                    ",
    "         OOO        ",
    "        OWWWO       ",
    "        OWWWO       ",
    "         OOO        ",
    "          O         ",
    "    OOOOOOOOO       ",
    "    O  PPPP  O      ",
    "    OOOOOOOOO       ",
    "     O     O        ",
    "     O     O        ",
    "    OOO   OOO       ",
    "   O   O O   O      ",
    "                    ",
    "                    ",
  ],

  'health-reckoning': [
    "                    ",
    "                    ",
    "                    ",
    "      OOOOOOO       ",
    "     OGGGGGGO       ",
    "     OGGGGGGO       ",
    "   OOOOOOOOOOOOO    ",
    "   OGGGGGGGGGGO     ",
    "   OGGGGGGGGGGO     ",
    "   OOOOOOOOOOOOO    ",
    "      OGGGGGGO      ",
    "      OGGGGGGO      ",
    "      OOOOOOO       ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'second-act': [
    "                    ",
    "                    ",
    "   OOOOOOOOOOOOO    ",
    "   OWWWWWWWWWWWO    ",
    "   OWWWWWWWWWWWO    ",
    "   OWWOOOWWWWWWO    ",
    "   OWWWWWWWWWWWO    ",
    "   OWWWOOOWWWWWO    ",
    "   OWWWWWWWWWWWO    ",
    "   OOOOOOOOOOOOO    ",
    "    O          O    ",
    "     OO      OO     ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
  ],

  // ── Category fallbacks (used when no node-specific sprite matches) ──

  'childhood': [
    "                    ",
    "       OOOO         ",
    "      OWWWWO        ",
    "      OW OWO        ",
    "      OWWWWO        ",
    "       OOOO         ",
    "        OO          ",
    "   OO OOOOOO OO     ",
    "   OOOOPPPPOOOO     ",
    "      OPPPPPO       ",
    "       OPPPO        ",
    "       OO OO        ",
    "      OO   OO       ",
    "     OOO   OOO      ",
    "                    ",
    "                    ",
  ],

  'childhood_alt1': [
    "                    ",
    "                    ",
    "        OO          ",
    "       OOOO         ",
    "      OOPPOO        ",
    "     OOOPPOO        ",
    "    O   OO   O      ",
    "    O  OOOO  O      ",
    "     OOPPPPOO       ",
    "      OPPPPO        ",
    "       OOOO         ",
    "      O    O        ",
    "     O      O       ",
    "    OOOO  OOOO      ",
    "                    ",
    "                    ",
  ],

  'education': [
    "                    ",
    "                    ",
    "      PPPPPPPP      ",
    "     PPPPPPPPPP     ",
    "    PPPPPPPPPPPP    ",
    "   OOOOOOOOOOOOOO   ",
    "       O    O       ",
    "    OOOOOOOOOOO     ",
    "    OWWWWWWWWWO     ",
    "    OWSSOWWSSO      ",
    "    OWSSOWWSSO      ",
    "    OWWWWWWWWO      ",
    "    OWWSSWWWWO      ",
    "    OOOOOOOOOOO     ",
    "                    ",
    "                    ",
  ],

  'education_alt1': [
    "                    ",
    "                    ",
    "    OOOO OOOO       ",
    "    OBBO OBBO       ",
    "    OBBO OBBO       ",
    "    OBBOOOBBO       ",
    "    OBBBBBBO        ",
    "    OBBBBBBO        ",
    "    OBBBBBBO        ",
    "    OOOOOOOO        ",
    "       OOOO         ",
    "      OYYYOO        ",
    "       OOOO         ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'career': [
    "                    ",
    "                    ",
    "   OOOOOOOOOOOOO    ",
    "   OSSSSSSSSSSSO    ",
    "   OSOOOOOOOOSOO    ",
    "   OSOWWWWWWOSO     ",
    "   OSOWWWWWWOSO     ",
    "   OSOWWWWWWOSO     ",
    "   OSOOOOOOOOSO     ",
    "   OSSSSSSSSSSSO    ",
    "   OOOOOOOOOOOOO    ",
    "       OOOOO        ",
    "     OOOOOOOOO      ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'career_alt1': [
    "                    ",
    "                    ",
    "    OOOOOOOOO       ",
    "    OBBBBBBBBO      ",
    "   OBBBBBBBBBBO     ",
    "   OBBWWWWWBBBO     ",
    "   OBBWSSWWBBBO     ",
    "   OBBWWWWWBBBO     ",
    "   OBBBBBBBBBBO     ",
    "    OBBBBBBBBO      ",
    "     OOOOOOO        ",
    "     O     O        ",
    "     O     O        ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'career_alt2': [
    "                    ",
    "                    ",
    "     OOOO           ",
    "    OYYYYO          ",
    "    OYYYYO          ",
    "     OOOO           ",
    "      OO            ",
    "   OOOOOOO          ",
    "   OWWWWWWO         ",
    "   OWWWWWWO         ",
    "   OOOOOOO          ",
    "     O  O           ",
    "    OO  OO          ",
    "    OO  OO          ",
    "                    ",
    "                    ",
  ],

  'relationship': [
    "                    ",
    "     OOO    OOO     ",
    "    ORRRO  ORRRO    ",
    "   ORRRRROORRRRRO   ",
    "   ORRRRRRRRRRRRO   ",
    "   ORRRWWRRRRRRRO   ",
    "    ORRWRRRRRRRO    ",
    "     ORRRRRRRRRO    ",
    "      ORRRRRRO      ",
    "       ORRRO        ",
    "        ORO         ",
    "         O          ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'relationship_alt1': [
    "                    ",
    "                    ",
    "      OOO  OOO      ",
    "     OWWO OWWO      ",
    "     OW OOW WO      ",
    "      OWWWWWO       ",
    "       OOOO         ",
    "      OOOOOO        ",
    "     OPPPPPPPO      ",
    "     OPPPPPPO       ",
    "      OPPPPO        ",
    "       OOOO         ",
    "      OO  OO        ",
    "     OO    OO       ",
    "                    ",
    "                    ",
  ],

  'health': [
    "                    ",
    "                    ",
    "                    ",
    "      OOOOOOO       ",
    "      OGGGGGGO      ",
    "      OGGGGGGO      ",
    "   OOOOOOOOOOOOO    ",
    "   OGGGGGGGGGGGO    ",
    "   OGGGGGGGGGGGO    ",
    "   OOOOOOOOOOOOO    ",
    "      OGGGGGGO      ",
    "      OGGGGGGO      ",
    "      OOOOOOO       ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'health_alt1': [
    "                    ",
    "                    ",
    "      OOO           ",
    "     OGGGO          ",
    "      OOO           ",
    "       O            ",
    "       O            ",
    "  OOOOOOOOOOOO      ",
    "  OGGGGGGGGGGO      ",
    "  OGGGGGGGGGGO      ",
    "  OOOOOOOOOOOO      ",
    "      O    O        ",
    "     OOO  OOO       ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'random': [
    "                    ",
    "                    ",
    "      OOOOOO        ",
    "    OO PPPP OO      ",
    "   OO PPPPPP OO     ",
    "   OO PP  PP OO     ",
    "   OOO    PP OO     ",
    "         PP OO      ",
    "        PP OO       ",
    "       PP OO        ",
    "       OOOO         ",
    "                    ",
    "       OOOO         ",
    "       OPPO         ",
    "       OOOO         ",
    "                    ",
  ],

  'random_alt1': [
    "                    ",
    "                    ",
    "      OOOOOO        ",
    "     OYYYYYO        ",
    "    OYYYYYYYOO      ",
    "    OYYY  YYYO      ",
    "    OYYYYYYYOO      ",
    "     OYYYYYO        ",
    "      OOOOOO        ",
    "   OOO  OO  OOO     ",
    "   OPPPOOPPPPO      ",
    "    OOOOOOOOOO      ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
  ],

  'decision': [
    "                    ",
    "                    ",
    "                    ",
    "       OOOO         ",
    "      OYYYO         ",
    "     OYYYYYOO       ",
    "    O   YY    O     ",
    "   O    YY     O    ",
    "    O   YY    O     ",
    "     OYYYYYOO       ",
    "      OYYYO         ",
    "       OOOO         ",
    "                    ",
    "                    ",
    "                    ",
    "                    ",
  ],
};

// Maps node IDs to alternate sprite keys for variety
export const NODE_SPRITE_MAP: Record<string, string> = {
  'childhood-1':       'childhood',
  'childhood-2':       'childhood_alt1',
  'childhood-3':       'education_alt1',
  'teenage-1':         'education',
  'teen-study-payoff': 'education_alt1',
  'teen-social-payoff':'relationship_alt1',
  'teen-rebel-payoff': 'health_alt1',
  'education-decision':'decision',
  'university-path':   'university-path',
  'work-path':         'work-path',
  'art-path':          'art-path',
  'travel-path':       'travel-path',
  'career-decision':   'decision',
  'corporate-path':    'corporate-path',
  'stable-path':       'career_alt1',
  'creative-career-path':'creative-career-path',
  'entrepreneur-path': 'entrepreneur-path',
  'work-life-decision':'decision',
  'relationship-decision':'relationship-decision',
  'married-young':     'relationship',
  'single-focused':    'career_alt2',
  'cohabitation':      'relationship_alt1',
  'family-decision':   'family-decision',
  'parent-path':       'childhood',
  'childless-path':    'career_alt2',
  'adoption-path':     'relationship',
  'midlife-crisis':    'midlife-crisis',
  'midlife-career':    'decision',
  'health-reckoning':  'health-reckoning',
  'late-career-1':     'career_alt1',
  'second-act':        'second-act',
  'retirement':        'retirement',
  'health-decline':    'health_alt1',
};
